export const dummyIngredients = [
  {
    id: 1,
    name: "Chicken Breast",
    category: "Protein",
    quantity: 2,
    unit: "lbs",
    expiryDate: "2024-09-15",
    location: "Refrigerator",
  },
  {
    id: 2,
    name: "Broccoli",
    category: "Vegetable",
    quantity: 1,
    unit: "head",
    expiryDate: "2024-09-12",
    location: "Refrigerator",
  },
  {
    id: 3,
    name: "Spaghetti",
    category: "Grain",
    quantity: 500,
    unit: "g",
    expiryDate: "2025-03-20",
    location: "Pantry",
  },
  {
    id: 4,
    name: "Parmesan Cheese",
    category: "Dairy",
    quantity: 200,
    unit: "g",
    expiryDate: "2024-10-01",
    location: "Refrigerator",
  },
  {
    id: 5,
    name: "Olive Oil",
    category: "Oil",
    quantity: 1,
    unit: "bottle",
    expiryDate: "2025-06-15",
    location: "Pantry",
  },
  {
    id: 6,
    name: "Eggs",
    category: "Protein",
    quantity: 12,
    unit: "count",
    expiryDate: "2024-09-18",
    location: "Refrigerator",
  },
];