services:
  # llm_api:
  #   build: 
  #     dockerfile: ../deployment/Dockerfile.llm-api
  #     context: ../llm_api
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./output:/app/output
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DB_NAME=llm_api
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   shm_size: '2gb'  # Important for Chromium
  #   networks:
  #     - fm-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      SCRIPT_NAME: /pgadmin
    ports:
      - "5432:5432"
    networks:
      - fm-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/:/docker-entrypoint-initdb.d/:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - fm-net
    volumes:
      - ./configs/pgadmin/pgpass:/pgadmin4/pgpass
      - ./configs/pgadmin/servers.json:/pgadmin4/servers.json

  ollama:
    image: ollama/ollama
    container_name: fm-llm
    ports:
      - "11434:11434"
    networks:
      - fm-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama-models:/root/.ollama
      - ./configs/ollama/entry.sh:/entry.sh:ro
    entrypoint: ["/bin/sh", "/entry.sh"]
    env_file:
      - .env

  chromadb:
    image: chromadb/chroma:1.0.18.dev24
    container_name: chroma_db
    ports:
      - "8000:8000"
    networks:
      - fm-net
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chromadb_data:/data/

volumes:
  postgres_data:
  ollama-models:
  chromadb_data:

networks:
  fm-net:
    driver: bridge