FROM python:3.12.0

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt && playwright install chromium --with-deps

COPY . .

CMD ["sh", "-c", "alembic upgrade head && python main.py"]
