location /fm/api/v1/chatters {
    content_by_lua_block {
        ngx.header["Access-Control-Allow-Origin"] = "*"
        ngx.header["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
        ngx.header["Access-Control-Allow-Headers"] = "Content-Type"

        local file_path = "/usr/local/openresty/nginx/html/mock-data/chatters.json"

        local file = io.open(file_path, "r")
        if not file then
            ngx.status = 404
            ngx.say("File not found")
            return
        end

        local content = file:read("*a")
        file:close()
        ngx.header.content_type = "application/json"
        ngx.say(content)
    }
}

location ~ ^/fm/api/v1/chatters/(\d+)$ {
    content_by_lua_block {
        ngx.header["Access-Control-Allow-Origin"] = "*"
        ngx.header["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
        ngx.header["Access-Control-Allow-Headers"] = "Content-Type"
        
        local chatter_id = ngx.re.match(ngx.var.uri, [[^/fm/api/v1/chatters/(\d+)]])
        if not chatter_id then
            ngx.status = 400
            ngx.say("Invalid request")
            return
        end

        local file_path = "/usr/local/openresty/nginx/html/mock-data/chatter-" .. chatter_id[1] .. ".json"
        local file = io.open(file_path, "r")

        if not file then
            ngx.status = 404
            ngx.say("User not found")
            return
        end

        local content = file:read("*a")
        file:close()

        ngx.header.content_type = "application/json"
        ngx.say(content)
    }
}
