# Generated by Django 5.0.1 on 2025-10-26 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(choices=[('grams', 'Grams'), ('lbs', 'Pounds'), ('ml', 'Milliliters'), ('pieces', 'Pieces'), ('cups', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons')], max_length=50)),
                ('category', models.CharField(blank=True, choices=[('dairy', 'Dairy'), ('produce', 'Produce'), ('meat', 'Meat'), ('spices', 'Spices'), ('grains', 'Grains'), ('other', 'Other')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'ingredients',
                'indexes': [models.Index(fields=['name'], name='idx_ingredients_name'), models.Index(fields=['category'], name='idx_ingredients_category')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('servings', models.IntegerField(default=1)),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('favorite', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'recipes',
                'indexes': [models.Index(fields=['name'], name='idx_recipes_name')],
            },
        ),
        migrations.CreateModel(
            name='PreparedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='servings', max_length=50)),
                ('prepared_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('counter', 'Counter')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('opened', 'Opened'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='fresh', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_items', to='food_management.recipe')),
            ],
            options={
                'db_table': 'prepared_food',
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50, null=True)),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='food_management.preparedfood')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='food_management.recipe')),
            ],
            options={
                'db_table': 'meal_logs',
            },
        ),
        migrations.CreateModel(
            name='IngredientInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('counter', 'Counter')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='food_management.ingredient')),
            ],
            options={
                'db_table': 'ingredient_inventory',
                'indexes': [models.Index(fields=['ingredient'], name='idx_inventory_ingredient'), models.Index(fields=['expiration_date'], name='idx_inventory_expiration'), models.Index(fields=['location'], name='idx_inventory_location')],
            },
        ),
        migrations.AddIndex(
            model_name='preparedfood',
            index=models.Index(fields=['name'], name='idx_prepared_food_name'),
        ),
        migrations.AddIndex(
            model_name='preparedfood',
            index=models.Index(fields=['recipe'], name='idx_prepared_food_recipe'),
        ),
        migrations.AddIndex(
            model_name='preparedfood',
            index=models.Index(fields=['expiration_date'], name='idx_prepared_food_expiration'),
        ),
        migrations.AddIndex(
            model_name='preparedfood',
            index=models.Index(fields=['status'], name='idx_prepared_food_status'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['recipe', 'meal_date'], name='idx_meal_log_recipe_date'),
        ),
    ]
