# Generated by Django 5.0.1 on 2025-10-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_management', '0002_recipeingredient'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['prepared_food', 'meal_date'], name='idx_meal_log_pre_food_date'),
        ),
    ]
