"""remove_qty_unit_from_ingredients

Revision ID: 0ec33c946bd8
Revises: a0b1c2d3e4f5
Create Date: 2026-06-15 03:41:45.526870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ec33c946bd8'
down_revision: Union[str, Sequence[str], None] = 'a0b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('families_name_key'), 'families', type_='unique')
    op.alter_column('family_recipe_statuses', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('ingredients', 'quantity')
    op.drop_column('ingredients', 'unit')
    op.execute("DROP TYPE IF EXISTS unitenum")
    op.alter_column('recipe_ingredients', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'indigo'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('ingredients', sa.Column('unit', postgresql.ENUM('tsp', 'tbsp', 'fl_oz', 'cup', 'pint', 'quart', 'gallon', 'ml', 'liter', 'oz', 'lb', 'g', 'kg', 'whole', 'dozen', 'pinch', 'dash', 'clove', 'slice', 'bunch', 'can', 'package', 'bag', name='unitenum'), autoincrement=False, nullable=True))
    op.add_column('ingredients', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('family_recipe_statuses', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('families_name_key'), 'families', ['name'])
    # ### end Alembic commands ###
