"""Convert ingredients and instructions to list

Revision ID: ed1a893ca0fc
Revises: 13622ca01f66
Create Date: 2025-11-19 19:19:30.010368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1a893ca0fc'
down_revision: Union[str, Sequence[str], None] = '13622ca01f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  op.alter_column(
      "recipes",
      "ingredients",
      type_=postgresql.JSONB(),
      postgresql_using="to_jsonb(ingredients)"
  )
  op.alter_column(
      "recipes",
      "instructions",
      type_=postgresql.JSONB(),
      postgresql_using="to_jsonb(instructions)"
  )


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('recipes', 'instructions',
                  existing_type=postgresql.ARRAY(sa.String()),
                  type_=sa.TEXT(),
                  existing_nullable=False)
  op.alter_column('recipes', 'ingredients',
                  existing_type=postgresql.ARRAY(sa.String()),
                  type_=sa.TEXT(),
                  existing_nullable=False)
  # ### end Alembic commands ###
